import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/molecules/header";
import classNames from "classnames";
import Footer from "@/components/molecules/footer";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    const fontsClass = classNames(raleway.className)
    return (
        <html lang="en">
            <body className={fontsClass}>
                <Header />
                <main className="container">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
